name: Lint + Unit Test

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Lint Tools
        run: |
          pip install black flake8

      - name: Run Black
        run: black . --check

      - name: Run Flake8
        run: flake8 .


  test:
    name: Unit Tests (ERPNext)
    runs-on: ubuntu-latest
    needs: lint

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Bench
        run: pip install frappe-bench

      - name: Init Bench
        run: bench init frappe-bench --frappe-branch version-15

      - name: Setup Site
        run: |
          cd frappe-bench
          bench new-site teststackerp --admin-password admin --db-root-password root
          bench get-app testerp2 $GITHUB_WORKSPACE
          bench --site teststackerp install-app testerp2

      - name: Run Tests
        run: |
          cd frappe-bench
          bench --site teststackerp run-tests --app testerp2